-- local ok, lsp_signature = pcall(require, "lsp_signature")
-- if not ok then return end
--
-- lsp_signature.setup({
--     bind = true,
--     handler_opts = {
--         border = "rounded"
--     },
--     hint_enable = true,
--     hint_prefix = "󰏪 ",
--     floating_window = true,
--     floating_window_above_cur_line = true,
--     toggle_key = '<C-k>',
-- })
